module.exports = {
  usinagem: {
    endpoint: 'opc.tcp://Cel_Usinagem:4840',
    ordem: 'ns=4;s=PLC1.Usinagem_IDentradaMES',
    produto: 'ns=4;s=PLC1.Usinagem_IdProduto',
    nome: 'ns=4;s=PLC1.Usinagem_String1',
    texto: 'ns=4;s=PLC1.Usinagem_String2',
    pressao: '',
    vazao: '',
    energia: '',
  },
  gravacao: {
    endpoint: 'opc.tcp://GRAVACAO_SENAI:4840',
    ordem: 'ns=4;s=Gravacao_IdEntradaMes',
    produto: 'ns=4;s=PLC1.Gravacao_ProductTag',
    nome: 'ns=4;s=PLC1.Gravacao_String2',
    texto: 'ns=4;s=PLC1.Gravacao_String2',
    pressao: '',
    vazao: '',
    energia: '',
  },
  embalagem: {
    endpoint: 'opc.tcp://Cel_Embalagem:4840',
    ordem: 'ns=4;s=PLC1.Embalagem_IdEntradaMes',
    produto: 'ns=4;s=PLC1.Embalagem_ProductTag',
    nome: 'ns=4;s=PLC1.Embalagem_String1',
    texto: 'ns=4;s=PLC1.Embalagem_String2',
    pressao: 'ns=4;s=PLC1.Embalagem_Pressostato',
    vazao: '',
    energia: '',
  },
  entrega: {
    endpoint: 'opc.tcp://Cel_Entrega:4840',
    ordem: 'ns=4;s=GVL.Entrega_IdEntradaMes',
    produto: 'ns=4;s=GVL.Entrega_ProductTag',
    nome: 'ns=4;s=GVL.Entrega_String1',
    texto: 'ns=4;s=GVL.Entrega_String2',
    pressao: 'ns=4;s=PLC1.Embalagem_Pressostato',
    vazao: '',
    energia: '',
  },
};
